services:
  l2guide-bot:
    build: .
    container_name: l2guide-bot
    restart: unless-stopped
    ports:
      - "3100:3100"
    env_file:
      - .env
    privileged: true
    volumes:
      - ./data/kb:/app/data/kb
    networks:
      - confiber-net

networks:
  confiber-net:
    external: true
